name: Upload-Python-Package

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.7', '3.8', '3.9', '3.10', '3.11']

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
          python-version: ${{ matrix.python-version }}

    - uses: actions/checkout@v2
    - uses: nanasess/setup-chromedriver@v2
      with:
        chromedriver-version: ${{ vars.CHROME_VERSION }}

    - name: setup chrome-driver Linux
      if: runner.os == 'Linux'
      run: |
        export DISPLAY=:99
        chromedriver --url-base=/wd/hub &
        sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional

    - name: setup chrome-driver MacOS
      if: runner.os == 'macOS'
      run: |
        export DISPLAY=:99
        chromedriver --url-base=/wd/hub &
        sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional

    - name: setup chrome-driver Windows
      if: runner.os == 'Windows'
      run: chromedriver --url-base=/wd/hub &

    - name: Update pip
      run: pip3 install --upgrade pip

    - name: Install dependencies
      run: pip3 install -r requirements_dev.txt

    - name: Run tests and show coverage
      run: |
        coverage run --source=base_page -m pytest tests/unit_tests.py tests/functional_tests.py --cache-clear
        coverage report -m

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

    - name: Publish package
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        python3 setup.py sdist bdist_wheel
        twine upload dist/*

