name: Upload Python Package

on:
  push

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.9', '3.10', '3.11']
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
          python-version: ${{ matrix.python-version }}

    - name: Update pip
      run: pip3 install --upgrade pip

    - name: Install dependencies
      run: pip3 install -r requirements_dev.txt

    # - name: Install chromedriver
    #   run: |
    #     curl -sS -o chromedriver_linux64.zip https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/116.0.5845.96/linux64/chromedriver-linux64.zip
    #     unzip chromedriver_linux64.zip
    #     rm chromedriver_linux64.zip
    #     sudo mv chromedriver-linux64/chromedriver /usr/local/bin/

    # - name: Run tests
    #   run: pytest tests/unit_tests.py

    - name: Install the library
      shell: bash
      run: python3 setup.py install

    # - name: Publish package
    #   uses: pypa/gh-action-pypi-publish@release/v0.1
    #   with:
    #     user: __token__
    #     password: ${{ secrets.PYPI_API_TOKEN }}
