name: Upload Python Package

on:
  push

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.9', '3.10', '3.11']
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
          python-version: ${{ matrix.python-version }}

    - name: Update pip
      run: pip3 install --upgrade pip

    - name: Install dependencies
      run: pip3 install -r requirements_dev.txt

    - name: Run tests
      run: pytest

    - name: Install the library
      shell: bash
      run: python3 setup.py install

    # - name: Publish package
    #   uses: pypa/gh-action-pypi-publish@release/v0.1
    #   with:
    #     user: __token__
    #     password: ${{ secrets.PYPI_API_TOKEN }}
